# Copyright (c) 2011-2021 Columbia University, System Level Design Group
# SPDX-License-Identifier: Apache-2.0
EXTRA_CFLAGS ?= -I$(ESP_ROOT)/accelerators/stratus_hls/fft_stratus/sw/linux/include
EXTRA_CFLAGS += -I$(ESP_ROOT)/accelerators/stratus_hls/spmv_stratus/sw/linux/include
EXTRA_CFLAGS += -I$(ESP_ROOT)/accelerators/stratus_hls/sort_stratus/sw/linux/include
EXTRA_CFLAGS += -I$(ESP_ROOT)/accelerators/stratus_hls/nightvision_stratus/sw/linux/include
EXTRA_CFLAGS += -I$(ESP_ROOT)/accelerators/stratus_hls/cholesky_stratus/sw/linux/include
EXTRA_CFLAGS += -I$(ESP_ROOT)/accelerators/stratus_hls/mriq_stratus/sw/linux/include
EXTRA_CFLAGS += -I$(ESP_ROOT)/accelerators/stratus_hls/vitdodec_stratus/sw/linux/include
EXTRA_CFLAGS += -I$(ESP_ROOT)/accelerators/stratus_hls/conv2d_stratus/sw/linux/include
EXTRA_CFLAGS += -I$(ESP_ROOT)/accelerators/stratus_hls/gemm_stratus/sw/linux/include
EXTRA_CFLAGS += -I$(ESP_ROOT)/accelerators/hls4ml/svhn_mlp_hls4ml/sw/linux/include
APPNAME := multiacc
include $(DRIVERS)/common.mk
