# Copyright (c) 2011-2021 Columbia University, System Level Design Group
# SPDX-License-Identifier: Apache-2.0
EXTRA_CFLAGS ?= -I$(ESP_ROOT)/accelerators/hls4ml/svhn_mlp_hls4ml/sw/linux/include
EXTRA_CFLAGS += -I$(ESP_ROOT)/accelerators/hls4ml/svhn_autoenc_hls4ml/sw/linux/include
EXTRA_CFLAGS += -I$(ESP_ROOT)/accelerators/stratus_hls/nightvision_stratus/sw/linux/include
APPNAME := comp_vision
include $(DRIVERS)/common.mk
